stages:
  Data_Download_Pipeline:
    cmd: python src\audio_testing\pipelines\data_download_pipeline.py
    deps:
      - src\audio_testing\pipelines\data_download_pipeline.py
      - yaml_files/paths_config.yaml
    outs:
      - artifacts


  # Data_Processing_Pipeline:
  #   cmd: python src/audio_testing/pipelines/data_redemption_pipeline.py
  #   deps:
  #     - src/audio_testing/pipelines/data_redemption_pipeline.py
  #     - yaml_files/paths_config.yaml
  #   outs:
  #     - artifacts
  #   # params:
  #   #   - SAVE_FORMAT
  #   #   - SAVE_DF_NAME

  # Data_Reduction_Pipeline:
  #   cmd: python src/audio_testing/pipelines/data_reduction_pipeline.py
  #   deps:
  #    - src/audio_testing/pipelines/data_reduction_pipeline.py
  #    - yaml_files/paths_config.yaml



# - src/audio_testing/implement/data_download_implement.py

