model_training:
  train_fraction: 0.8
  valid_fraction: 0.1
  test_fraction: 0.1
  device: "cpu"
  # optimizer: IDK how to do that ^_^:)
  # criterion: 
  num_epochs: 10
  batch_size: 8
  input_size: 10000
  # save_model_with_name